plugins { id 'com.android.application' }

android { namespace 'za.co.getwiredautoworx.owner'; compileSdk 35
    defaultConfig { applicationId 'za.co.getwiredautoworx.owner'; minSdk 23; targetSdk 35; versionCode 3; versionName '1.0.2' }
    buildTypes {
        debug {
            applicationIdSuffix '.test'
            versionNameSuffix '-test'
        }
    }
}
